
export enum CollectionsEnum {
  SHORT_ESTABLISHMENTS = "SHORT_ESTABLISHMENTS",
  SHORT_PARKINGS = "SHORT_PARKINGS",
  APP_INFO = "APP_INFO",
  USERS = 'USERS',
  SUGGESTIONS_BAIXADA_SANTISTA = 'SUGGESTIONS_BAIXADA_SANTISTA'
}
